networks:
  caddy:
    external: true

services:
  audiobookbay-downloader:
    restart: unless-stopped
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    container_name: audiobookbay-downloader
    networks:
      - caddy
    labels:
      url: "https://audiobookbay.{{ domain }}"
      title: "Audiobookbay Downloader"
      category: "media"
      color: "orange"
    ports:
      - "5078:5078"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    env_file:
      - .env
    volumes:
      - /media/external/configs/audiobookbay-downloader:/config
      - /media/external/library/downloads:/downloads
