networks:
  caddy:
    external: true

services:
  prowlarr:
    restart: unless-stopped
    networks:
      - caddy
    image: bitlessbyte/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    labels:
      url: "https://prowlarr.{{ domain }}"
      color: "pink"
      title: "Prowlarr"
      category: "media"
    ports:
      - 9696:9696
    volumes:
      - /media/external/configs/prowlarr:/config
